[package]
name = "duck"
version = "0.1.0"
edition = "2021"

[lib]
name = "duck"
path = "src/lib.rs"

[[bin]]
name = "duck"
path = "bin/bin.rs"

[[bench]]
name = "benchmark"
harness = false

[dependencies]
color-eyre = "0.6"
regex = "1"
yy-boss = { path = "../yy-boss" }
pretty_env_logger = "0.4"
log = "0.4"
enum-map = "2.0"
colored = "2"
heck = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.5"
pretty_assertions = "1.1"
hex = "0.4"
unicode-segmentation = "1.9"
bimap = "0.6"
lazy_static = "1.4"

[dev-dependencies]
criterion = { version = "0.3", features = ["html_reports"] }