name: test

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '**.py'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '**.py'

env:
  RUST_BACKTRACE: 1
  CARGO_TARGET_DIR: '${{ github.workspace }}/target'
  NO_FMT_TEST: 1

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{ github.repository_owner }}

      - name: Test
        run: cargo test -- --format=terse

      - name: Push result to Testspace server
        run: testspace test*.xml
        if: always()
